# Fase 3: Núcleo Algorítmico, Eficiencia y Programación Orientada a Objetos

## Proyecto: Análisis de Sismicidad en Chile

### Objetivo General

Desarrollar un núcleo algorítmico modular para analizar eventos sísmicos en Chile utilizando programación estructurada, recursividad, programación orientada a objetos y análisis de eficiencia computacional.

### Contexto

Este notebook utiliza el dataset limpio generado en la Fase 2 y busca identificar, ordenar y clasificar eventos sísmicos relevantes según magnitud y profundidad. Además, incorpora mediciones de complejidad algorítmica, validaciones técnicas y una arquitectura modular basada en Programación Orientada a Objetos (POO).

In [1]:
import pandas as pd
import numpy as np
import timeit
from pathlib import Path

In [2]:
# Cargar dataset original

df = pd.read_csv("../data/processed/seismic_data_clean.csv")

print("Dataset cargado correctamente")
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

Dataset cargado correctamente
Filas: 4015
Columnas: 14

In [3]:
df.head()

,Date(UTC),Latitude,Longitude,Depth,Magnitude,Year,Month,Day,Hour,DayOfWeek,Depth_Category,Magnitude_Category,Depth_norm,Magnitude_norm
0,2025-05-26 03:50:27,-19.63,-69.49,97,5.6,2025,5,26,3,0,Intermedio,Fuerte,0.152733,0.540984
1,2025-05-13 00:47:58,-51.25,-72.28,28,5.1,2025,5,13,0,1,Superficial,Fuerte,0.041801,0.459016
2,2025-05-05 09:46:48,-29.49,-71.84,48,5.0,2025,5,5,9,0,Superficial,Moderado,0.073955,0.442623
3,2025-05-05 02:17:48,-31.89,-70.88,88,5.1,2025,5,5,2,0,Intermedio,Fuerte,0.138264,0.459016
4,2025-05-02 15:23:49,-27.52,-72.48,30,5.8,2025,5,2,15,4,Superficial,Fuerte,0.045016,0.573770

In [4]:
def cargar_datos(ruta):
    """
    Carga un archivo CSV y devuelve un DataFrame.

    Parámetros:
    ruta (str): ubicación del archivo CSV.

    Retorna:
    DataFrame con los datos cargados.
    """

    try:
        df = pd.read_csv(ruta)

        print("Archivo cargado correctamente")
        print(f"Registros: {df.shape[0]}")
        print(f"Columnas: {df.shape[1]}")

        return df

    except FileNotFoundError:
        print("Error: archivo no encontrado")

In [5]:
df = cargar_datos("../data/processed/seismic_data_clean.csv")

Archivo cargado correctamente
Registros: 4015
Columnas: 14

In [6]:
def analizar_dataset(df):
    """
    Muestra información general del dataset.
    """

    print("===== INFORMACIÓN GENERAL =====")
    print(f"Cantidad de filas: {df.shape[0]}")
    print(f"Cantidad de columnas: {df.shape[1]}")

    print("\n===== COLUMNAS =====")
    print(df.columns.tolist())

    print("\n===== VALORES NULOS =====")
    print(df.isnull().sum())

In [7]:
analizar_dataset(df)

===== INFORMACIÓN GENERAL =====
Cantidad de filas: 4015
Cantidad de columnas: 14

===== COLUMNAS =====
['Date(UTC)', 'Latitude', 'Longitude', 'Depth', 'Magnitude', 'Year', 'Month', 'Day', 'Hour', 'DayOfWeek', 'Depth_Category', 'Magnitude_Category', 'Depth_norm', 'Magnitude_norm']

===== VALORES NULOS =====
Date(UTC)             0
Latitude              0
Longitude             0
Depth                 0
Magnitude             0
Year                  0
Month                 0
Day                   0
Hour                  0
DayOfWeek             0
Depth_Category        0
Magnitude_Category    0
Depth_norm            0
Magnitude_norm        0
dtype: int64

In [8]:
def buscar_sismos_fuertes(df, magnitud_minima):
    """
    Retorna todos los sismos cuya magnitud
    sea mayor o igual al valor indicado.
    """

    resultado = df[df["Magnitude"] >= magnitud_minima]

    return resultado

In [9]:
sismos_fuertes = buscar_sismos_fuertes(df, 6.0)

print(f"Cantidad de sismos encontrados: {len(sismos_fuertes)}")

sismos_fuertes.head()

Cantidad de sismos encontrados: 121

,Date(UTC),Latitude,Longitude,Depth,Magnitude,Year,Month,Day,Hour,DayOfWeek,Depth_Category,Magnitude_Category,Depth_norm,Magnitude_norm
5,2025-05-02 12:58:32,-56.88,-68.06,10,7.5,2025,5,2,12,4,Superficial,Grande,0.012862,0.852459
7,2025-04-18 00:10:18,-23.47,-68.22,139,6.0,2025,4,18,0,4,Intermedio,Fuerte,0.220257,0.606557
16,2025-03-06 16:21:39,-23.33,-69.21,103,6.0,2025,3,6,16,3,Intermedio,Fuerte,0.162379,0.606557
29,2025-01-02 20:43:35,-21.73,-69.04,98,6.0,2025,1,2,20,3,Intermedio,Fuerte,0.154341,0.606557
37,2024-12-13 23:38:18,-35.34,-70.87,114,6.3,2024,12,13,23,4,Intermedio,Mayor,0.180064,0.655738

## Validación técnica de la función buscar_sismos_fuertes

Se evalúan tres escenarios:

- Caso normal.
- Caso límite.
- Caso de excepción.

El objetivo es verificar que la función responde correctamente bajo distintas condiciones.

In [10]:
# Caso normal

resultado_normal = buscar_sismos_fuertes(df, 6.0)

print("Caso normal")
print(f"Sismos encontrados: {len(resultado_normal)}")

Caso normal
Sismos encontrados: 121

In [11]:
# Caso límite

resultado_limite = buscar_sismos_fuertes(df, 10.0)

print("Caso límite")
print(f"Sismos encontrados: {len(resultado_limite)}")

Caso límite
Sismos encontrados: 0

In [12]:
try:
    buscar_sismos_fuertes(df, "seis")

except Exception as e:
    print("Excepción capturada correctamente")
    print(e)

Excepción capturada correctamente
Invalid comparison between dtype=float64 and str

## Medición de eficiencia algorítmica

Se comparan dos implementaciones para identificar sismos con magnitud mayor o igual a 6.0:

- Implementación con recorrido fila por fila.
- Implementación vectorizada con pandas.

El objetivo es medir el tiempo de ejecución y justificar la elección del método más eficiente.

In [13]:
def buscar_sismos_bucle(df, magnitud_minima):
    """
    Busca sismos fuertes recorriendo el DataFrame fila por fila.
    Esta implementación es menos eficiente porque evalúa cada registro individualmente en Python.
    """
    resultados = []

    for _, fila in df.iterrows():
        if fila["Magnitude"] >= magnitud_minima:
            resultados.append(fila)

    return resultados


def buscar_sismos_vectorizado(df, magnitud_minima):
    """
    Busca sismos fuertes usando operaciones vectorizadas de pandas.
    Esta implementación aprovecha optimizaciones internas y suele ser más eficiente.
    """
    return df[df["Magnitude"] >= magnitud_minima]

In [14]:
tiempo_bucle = timeit.timeit(
    lambda: buscar_sismos_bucle(df, 6.0),
    number=10
)

tiempo_vectorizado = timeit.timeit(
    lambda: buscar_sismos_vectorizado(df, 6.0),
    number=10
)

print("Tiempo con bucle:", tiempo_bucle)
print("Tiempo vectorizado:", tiempo_vectorizado)
print("Diferencia:", tiempo_bucle / tiempo_vectorizado)

Tiempo con bucle: 1.1968904999994265
Tiempo vectorizado: 0.004515800002991455
Diferencia: 265.0450638218159

## Algoritmo recursivo: Merge Sort

Para demostrar la aplicación de recursividad se implementa el algoritmo Merge Sort sobre la variable Magnitude.

Este algoritmo utiliza la estrategia divide y vencerás, dividiendo el problema en subproblemas más pequeños hasta alcanzar un caso base y posteriormente combinando los resultados ordenados.

In [15]:
def merge_sort(lista):

    if len(lista) <= 1:
        return lista

    medio = len(lista) // 2

    izquierda = merge_sort(lista[:medio])
    derecha = merge_sort(lista[medio:])

    return combinar(izquierda, derecha)


def combinar(izquierda, derecha):

    resultado = []
    i = 0
    j = 0

    while i < len(izquierda) and j < len(derecha):

        if izquierda[i] <= derecha[j]:
            resultado.append(izquierda[i])
            i += 1

        else:
            resultado.append(derecha[j])
            j += 1

    resultado.extend(izquierda[i:])
    resultado.extend(derecha[j:])

    return resultado

In [16]:
magnitudes = df["Magnitude"].tolist()

magnitudes_ordenadas = merge_sort(magnitudes)

print("Primeras 10 magnitudes ordenadas:")
print(magnitudes_ordenadas[:10])

print("\nÚltimas 10 magnitudes ordenadas:")
print(magnitudes_ordenadas[-10:])

Primeras 10 magnitudes ordenadas:
[2.3, 2.6, 2.6, 2.6, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8]

Últimas 10 magnitudes ordenadas:
[7.0, 7.1, 7.1, 7.4, 7.5, 7.6, 7.6, 7.6, 8.2, 8.4]

In [ ]:
# Generar archivo de resultados de eficiencia

resultados_eficiencia = pd.DataFrame({
    "metodo": ["bucle_iterrows", "vectorizado_pandas"],
    "tiempo_segundos": [tiempo_bucle, tiempo_vectorizado],
    "magnitud_minima": [6.0, 6.0]
})

resultados_eficiencia["mejora_relativa"] = tiempo_bucle / tiempo_vectorizado

ruta_resultados = "resultados/metricas_eficiencia.csv"

resultados_eficiencia.to_csv(ruta_resultados, index=False)

print("Archivo generado correctamente:")
print(ruta_resultados)

resultados_eficiencia

Archivo generado correctamente:
resultados/metricas_eficiencia.csv

               metodo  tiempo_segundos  magnitud_minima  mejora_relativa
0      bucle_iterrows         1.903577              6.0       189.850808
1  vectorizado_pandas         0.010027              6.0       189.850808

## Pipeline integrado

Se compone un `Pipeline` con las etapas de transformación definidas
anteriormente. El Pipeline ejecuta cada etapa en orden sin conocer su
tipo concreto, demostrando composición y polimorfismo trabajando
juntos para construir el dataset final de análisis.

In [ ]:
import sys
sys.path.append("src")

from orquestador import Pipeline
from transformadores import (
    ClasificadorMagnitudAlta,
    ClasificadorProfundidad,
    NormalizadorMinMax,
)
from pipeline import AnalizadorSismicoAvanzado

# Se compone el pipeline con las etapas necesarias
pipeline = Pipeline([
    ClasificadorMagnitudAlta(umbral=6.0),
    ClasificadorProfundidad(),
    NormalizadorMinMax(columnas=["Depth", "Magnitude"]),
])

df_final = pipeline.ejecutar(df)

print()
print("Forma final del dataset:", df_final.shape)
df_final.head()

✅ Etapa ejecutada: ClasificadorMagnitudAlta
✅ Etapa ejecutada: ClasificadorProfundidad
✅ Etapa ejecutada: NormalizadorMinMax

Forma final del dataset: (4015, 16)

,Date(UTC),Latitude,Longitude,Depth,Magnitude,Year,Month,Day,Hour,DayOfWeek,Depth_Category,Magnitude_Category,Depth_norm,Magnitude_norm,Sismo_Fuerte,Categoria_Profundidad
0,2025-05-26 03:50:27,-19.63,-69.49,97,5.6,2025,5,26,3,0,Intermedio,Fuerte,0.152733,0.540984,False,Intermedio
1,2025-05-13 00:47:58,-51.25,-72.28,28,5.1,2025,5,13,0,1,Superficial,Fuerte,0.041801,0.459016,False,Superficial
2,2025-05-05 09:46:48,-29.49,-71.84,48,5.0,2025,5,5,9,0,Superficial,Moderado,0.073955,0.442623,False,Superficial
3,2025-05-05 02:17:48,-31.89,-70.88,88,5.1,2025,5,5,2,0,Intermedio,Fuerte,0.138264,0.459016,False,Intermedio
4,2025-05-02 15:23:49,-27.52,-72.48,30,5.8,2025,5,2,15,4,Superficial,Fuerte,0.045016,0.573770,False,Superficial

In [ ]:
analizador = AnalizadorSismicoAvanzado(df_final, umbral_fuerte=6.0)

print("📊 Resumen final del análisis:")
for clave, valor in analizador.resumen().items():
    print(f"  {clave}: {valor}")

📊 Resumen final del análisis:
  registros: 4015
  magnitud_maxima: 8.4
  profundidad_promedio: 61.53
  magnitud_promedio: 4.43
  sismos_fuertes: 121

## Bibliografía

- McKinney, W. (2022). *Python for Data Analysis* (3rd ed.). O'Reilly Media.
  https://wesmckinney.com/book/

- pandas development team. (2024). *pandas documentation*.
  https://pandas.pydata.org/docs/

- Python Software Foundation. (2024). *abc — Abstract Base Classes*.
  Python documentation. https://docs.python.org/3/library/abc.html

- Cormen, T. H., Leiserson, C. E., Rivest, R. L., & Stein, C. (2022).
  *Introduction to Algorithms* (4th ed.). MIT Press.

- Wirth, R., & Hipp, J. (2000). CRISP-DM: Towards a standard process
  model for data mining. Proceedings of the 4th International
  Conference on the Practical Applications of Knowledge Discovery
  and Data Mining.

# Conclusiones

## Resultados obtenidos

Se implementó un núcleo algorítmico para el análisis de sismos en Chile utilizando programación estructurada, recursividad y programación orientada a objetos.

La búsqueda de sismos fuertes fue desarrollada mediante dos enfoques:

- Implementación basada en bucles.
- Implementación vectorizada con pandas.

Los resultados demostraron que la solución vectorizada presentó un rendimiento significativamente superior.

## Recursividad

Se implementó Merge Sort para ordenar magnitudes sísmicas utilizando la estrategia divide y vencerás.

## Programación Orientada a Objetos

Se desarrollaron clases base y avanzadas que permiten encapsular la lógica de análisis sísmico, incorporando herencia y polimorfismo.

## Conclusión general

La arquitectura modular desarrollada facilita la reutilización de código, mejora la mantenibilidad del proyecto y permite escalar futuras funcionalidades analíticas.